/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { useState, useEffect, FormEvent, KeyboardEvent } from 'react';
import { Info, Sparkles, Send, CheckCircle2, Shuffle, Coins, Trophy, Calendar, Users, Copy, Check } from 'lucide-react';
import { PaymentMethod, Ticket, User } from '../types';
import { playClickSound, playTickSound, playSuccessSound } from '../utils/audio';

interface TicketSelectorProps {
  currentUser: User;
  tickets: Ticket[];
  onAddTicket: (ticket: Omit<Ticket, 'id' | 'createdAt' | 'status'>) => void;
  onUpdateCoins?: (amount: number, reason?: string) => void;
}

export default function TicketSelector({ currentUser, tickets, onAddTicket, onUpdateCoins }: TicketSelectorProps) {
  const [selectedDigits, setSelectedDigits] = useState<string[]>(['', '', '']);
  const [payWithCoins, setPayWithCoins] = useState<boolean>(false);
  const [txnId, setTxnId] = useState<string>('');
  const [generatedPaymentId, setGeneratedPaymentId] = useState<string>('');
  const [isSubmitSuccess, setIsSubmitSuccess] = useState<boolean>(false);
  const [errorMessage, setErrorMessage] = useState<string>('');
  const [copiedUpi, setCopiedUpi] = useState<boolean>(false);

  const upiId = '8509446186@ybl';
  const lotteryNumber = selectedDigits.join('');
  const currentCoins = currentUser.isAdmin ? 999999 : (currentUser.goldCoins ?? 0);

  const isNumberAlreadyTaken = lotteryNumber.length === 3 && tickets.some(t => t.number === lotteryNumber && t.status !== 'declined');
  const takenByTicket = lotteryNumber.length === 3 ? tickets.find(t => t.number === lotteryNumber && t.status !== 'declined') : undefined;

  // Dynamically compute a unique payment reference ID based on selected digits
  useEffect(() => {
    if (lotteryNumber.length === 3) {
      const namePart = (currentUser.name || 'USR').substring(0, 3).toUpperCase();
      const randomSuffix = Math.floor(100 + Math.random() * 900);
      setGeneratedPaymentId(`PAY-${lotteryNumber}-${namePart}-${randomSuffix}`);
    } else {
      setGeneratedPaymentId('');
    }
  }, [lotteryNumber, currentUser.name]);

  // Adjust payments toggle automatically if current coins drops below 30
  useEffect(() => {
    if (currentCoins < 30 && payWithCoins) {
      setPayWithCoins(false);
    }
  }, [currentCoins, payWithCoins]);

  const handleDigitChange = (value: string, index: number) => {
    if (!/^\d*$/.test(value)) return;
    const updated = [...selectedDigits];
    updated[index] = value.slice(-1);
    setSelectedDigits(updated);
    setErrorMessage('');

    if (value && index < 2) {
      const nextInput = document.getElementById(`digit-input-${index + 1}`) as HTMLInputElement;
      if (nextInput) nextInput.focus();
    }
  };

  const handleKeyDown = (e: KeyboardEvent<HTMLInputElement>, index: number) => {
    if (e.key === 'Backspace' && !selectedDigits[index] && index > 0) {
      const prevInput = document.getElementById(`digit-input-${index - 1}`) as HTMLInputElement;
      if (prevInput) {
        prevInput.focus();
        const updated = [...selectedDigits];
        updated[index - 1] = '';
        setSelectedDigits(updated);
      }
    }
  };

  const autoGenerateDigits = () => {
    let attempts = 0;
    let foundNumber = '';
    while (attempts < 50) {
      const code = Array.from({ length: 3 }, () => Math.floor(Math.random() * 10).toString()).join('');
      const isTaken = tickets.some(t => t.number === code && t.status !== 'declined');
      if (!isTaken) {
        foundNumber = code;
        break;
      }
      attempts++;
    }
    
    // Fallback if all lookups failed
    if (!foundNumber) {
      foundNumber = Array.from({ length: 3 }, () => Math.floor(Math.random() * 10).toString()).join('');
    }

    setSelectedDigits(foundNumber.split(''));
    setErrorMessage('');
    playClickSound();
  };

  const autofillTxnId = () => {
    const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
    let randomTxn = 'TXN';
    for (let i = 0; i < 8; i++) {
      randomTxn += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    setTxnId(randomTxn);
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(upiId);
    setCopiedUpi(true);
    setTimeout(() => setCopiedUpi(false), 2000);
  };

  const handleSubmit = (e: FormEvent) => {
    e.preventDefault();
    if (lotteryNumber.length !== 3) {
      setErrorMessage('Please select a complete 3-digit number.');
      return;
    }

    if (isNumberAlreadyTaken) {
      setErrorMessage(`This number (${lotteryNumber}) is already taken by ${takenByTicket?.userName || 'another user'}! Please select an exclusive number.`);
      return;
    }

    if (payWithCoins) {
      if (!currentUser.isAdmin && currentCoins < 30) {
        setErrorMessage('Insufficient Gold Coins. You need 30 coins to book a free ticket.');
        return;
      }

      onAddTicket({
        number: lotteryNumber,
        userEmail: currentUser.email,
        userName: currentUser.name,
        userAvatar: currentUser.photoURL,
        paymentMethod: 'Gold Coins',
        paymentId: `COIN-${lotteryNumber}-${(currentUser.name || 'USR').substring(0, 3).toUpperCase()}-${Math.floor(100 + Math.random() * 900)}`,
        txnId: `COINPASS-${Math.random().toString(36).substring(2, 8).toUpperCase()}`,
      });
    } else {
      if (!txnId.trim()) {
        setErrorMessage('Transaction ID (Txn ID) is required after completing the payment.');
        return;
      }

      onAddTicket({
        number: lotteryNumber,
        userEmail: currentUser.email,
        userName: currentUser.name,
        userAvatar: currentUser.photoURL,
        paymentMethod: 'UPI',
        paymentId: generatedPaymentId,
        txnId: txnId.trim(),
      });
    }

    setIsSubmitSuccess(true);
    setTimeout(() => {
      setIsSubmitSuccess(false);
      setSelectedDigits(['', '', '']);
      setTxnId('');
      setPayWithCoins(false);
    }, 4000);
  };

  return (
    <div className="space-y-6">
      {/* 🎫 TICKET CUSTOMIZATION FORM */}
      <div id="ticket-selector-card" className="rounded-2xl border border-purple-950/40 bg-black/40 p-6 backdrop-blur-md shadow-[0_0_30px_rgba(168,85,247,0.02)]">
        <h2 className="font-display text-base font-bold text-white mb-5 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Sparkles className="h-4 w-4 text-purple-400" />
            <span>Select & Book Ticket</span>
          </div>
          <span className="text-[9px] bg-purple-500/10 text-purple-405 border border-purple-500/20 px-2 py-0.5 rounded-full font-semibold uppercase tracking-wider">
            ₹100 or 🪙30 Free
          </span>
        </h2>

        {isSubmitSuccess ? (
          <div className="flex flex-col items-center justify-center py-10 text-center animate-in scale-in duration-200">
            <div className="flex h-12 w-12 items-center justify-center rounded-full bg-purple-500/10 border border-purple-500/20 text-purple-400 mb-3">
              <CheckCircle2 className="h-6 w-6" />
            </div>
            <h3 className="font-display text-base font-bold text-white mb-1">Ticket Submitted</h3>
            <p className="text-xs text-zinc-400 max-w-sm mb-4 leading-relaxed">
              {payWithCoins 
                ? "Your Gold Coin Payment has been verified. Since you paid with 30 Gold Coins, your ticket is AUTO-APPROVED and immediately activated!"
                : "Your ticket request and matching payment details have been logged. The moderator will verify and activate your ticket shortly."}
            </p>
            <div className="rounded-lg bg-black border border-purple-950/40 px-3.5 py-1.5 text-xs font-mono">
              Ticket Number: <span className="font-bold text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-red-500">{lotteryNumber}</span>
            </div>
            <div className="text-[10px] text-zinc-550 mt-4 animate-pulse">
              Refreshing forms in a moment...
            </div>
          </div>
        ) : (
          <form onSubmit={handleSubmit} className="space-y-5">
            
            {/* Step 1: Choose 3 Digits */}
            <div className="space-y-2.5">
              <div className="flex items-center justify-between">
                <label className="text-[11px] font-bold text-zinc-400 uppercase tracking-wider">1. Select Number</label>
                <button
                  type="button"
                  onClick={autoGenerateDigits}
                  className="inline-flex items-center gap-1.5 rounded-full bg-purple-950/25 border border-purple-500/25 px-3 py-1.5 text-[11px] font-bold text-purple-300 hover:bg-purple-900/40 hover:border-purple-500/50 hover:text-white transition-all active:scale-95 cursor-pointer select-none"
                >
                  <Shuffle className="h-3 w-3 text-purple-400" />
                  <span>Quick Pick</span>
                </button>
              </div>

              <div className="flex justify-between gap-1.5 sm:gap-2">
                {selectedDigits.map((digit, index) => (
                  <input
                    key={index}
                    id={`digit-input-${index}`}
                    type="text"
                    maxLength={1}
                    value={digit}
                    onChange={(e) => handleDigitChange(e.target.value, index)}
                    onKeyDown={(e) => handleKeyDown(e, index)}
                    className="h-12 w-full rounded-xl bg-black text-center font-display text-xl font-bold text-white border border-purple-950/40 focus:border-purple-500 focus:outline-none transition"
                    placeholder="?"
                  />
                ))}
              </div>
              {lotteryNumber.length === 3 && (
                <div className={`rounded-xl border p-3 flex gap-2.5 animate-in slide-in-from-top-1 duration-150 ${
                  isNumberAlreadyTaken
                    ? 'border-rose-500/30 bg-rose-500/5 text-rose-300'
                    : 'border-emerald-500/20 bg-emerald-500/5 text-emerald-300'
                }`}>
                  <div className="shrink-0 mt-0.5">
                    {isNumberAlreadyTaken ? (
                      <span className="text-xs">🚨</span>
                    ) : (
                      <span className="text-xs">✅</span>
                    )}
                  </div>
                  <div className="space-y-0.5 leading-snug">
                    <p className="text-[11px] font-extrabold tracking-wide uppercase select-none">
                      {isNumberAlreadyTaken ? 'Number Already Taken' : 'Exclusive Available Number'}
                    </p>
                    <p className="text-[10px] text-zinc-400">
                      {isNumberAlreadyTaken
                        ? `This number (${lotteryNumber}) was already claimed by ${takenByTicket?.userName || 'another member'}. Please choose a different unique combination!`
                        : `The code ${lotteryNumber} is 100% available and ready to book. Grab it first!`
                      }
                    </p>
                  </div>
                </div>
              )}

              {lotteryNumber.length < 3 && (
                <p className="text-[10px] text-zinc-400 flex items-start gap-1.5 leading-snug px-1 select-none">
                  <Info className="h-3.5 w-3.5 text-purple-400 shrink-0 mt-0.5" />
                  <span>Ticket numbers are exclusive. To ensure single winners per grand prize, once a number is booked by a user, no other person can take it!</span>
                </p>
              )}
            </div>

            {/* Choose Gateway Choice Section */}
            {lotteryNumber.length === 3 && !isNumberAlreadyTaken && (
              <div className="space-y-2 pt-1 animate-in slide-in-from-top-2 duration-150">
                <span className="text-[11px] font-bold text-zinc-400 uppercase tracking-wider block">2. Select Payment Method</span>
                <div className="grid grid-cols-2 gap-3">
                  <button
                    type="button"
                    onClick={() => {
                      setPayWithCoins(false);
                      playClickSound();
                    }}
                    className={`py-2 px-3 rounded-lg border text-xs font-bold transition flex items-center justify-center gap-1.5 cursor-pointer select-none ${
                      !payWithCoins
                        ? 'bg-purple-950/30 border-purple-500/40 text-white'
                        : 'bg-zinc-950 border-purple-950/10 text-zinc-500 hover:border-purple-950/30'
                    }`}
                  >
                    <span>💳 UPI Cash (₹100)</span>
                  </button>

                  <button
                    type="button"
                    disabled={!currentUser.isAdmin && currentCoins < 30}
                    onClick={() => {
                      setPayWithCoins(true);
                      playClickSound();
                    }}
                    className={`py-2 px-3 rounded-lg border text-xs font-bold transition flex items-center justify-center gap-1.5 cursor-pointer select-none relative ${
                      payWithCoins
                        ? 'bg-amber-950/30 border-amber-500/40 text-white shadow-[0_0_12px_rgba(245,158,11,0.08)]'
                        : (!currentUser.isAdmin && currentCoins < 30)
                        ? 'bg-zinc-950 border-zinc-900/50 text-zinc-650 cursor-not-allowed'
                        : 'bg-zinc-950 border-amber-950/10 text-amber-500/85 hover:border-amber-500/30 hover:text-amber-400'
                    }`}
                  >
                    <span>🪙 Coin Pass {currentUser.isAdmin ? '(Admin Unlimited)' : '(30)'}</span>
                    {(!currentUser.isAdmin && currentCoins < 30) && (
                      <span className="absolute -top-1.5 -right-1 leading-none text-[8px] tracking-wide bg-red-955 bg-black text-red-400 px-1 py-0.5 rounded border border-red-500/20 font-bold">
                        Locked
                      </span>
                    )}
                  </button>
                </div>
              </div>
            )}

            {/* Step 2 Details: QR / UPI Payment */}
            {lotteryNumber.length === 3 && !payWithCoins && (
              <div className="space-y-3.5 animate-in slide-in-from-top-2 duration-150">
                <label className="text-[11px] font-bold text-zinc-400 uppercase tracking-wider block">3. Checkout payment</label>
                
                <div className="rounded-xl border border-purple-950/30 bg-black/50 p-4 space-y-3.5 font-sans">
                  
                  {/* UPI ID Info */}
                  <div className="rounded-lg bg-black border border-purple-950/30 p-2.5 flex items-center justify-between">
                    <div>
                      <div className="text-[9px] text-zinc-550 font-bold uppercase tracking-wider font-mono">UPI address</div>
                      <div className="text-xs font-mono text-zinc-300 mt-0.5 select-all">{upiId}</div>
                    </div>
                    <button
                      type="button"
                      onClick={copyToClipboard}
                      className="text-[10px] font-semibold px-2 py-1 rounded bg-zinc-900 text-zinc-300 hover:bg-purple-950/40 hover:text-white transition cursor-pointer"
                    >
                      {copiedUpi ? 'Copied' : 'Copy'}
                    </button>
                  </div>

                  {/* Amount Guidance */}
                  <div className="text-xs text-zinc-405 leading-relaxed bg-black border border-purple-950/20 p-3 rounded-lg flex items-start gap-2">
                    <Info className="h-4 w-4 text-purple-400 shrink-0 mt-0.5" />
                    <p>
                      Please transfer exactly <strong className="text-white">₹ 100</strong> to book your chosen ticket <span className="font-mono text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-red-500 text-xs font-bold bg-black px-1.5 py-0.5 rounded border border-purple-950/30">{lotteryNumber}</span>. Include reference key in the transfer memo.
                    </p>
                  </div>

                  {/* Unique key for verification */}
                  <div className="rounded-lg bg-black border border-purple-950/30 p-2.5">
                    <div className="text-[9px] text-zinc-550 font-bold uppercase tracking-wider font-mono">Reference Key</div>
                    <div className="flex items-center justify-between mt-0.5">
                      <div className="text-xs font-mono font-bold text-purple-400 bg-purple-500/5 px-2 py-0.5 rounded border border-purple-500/10 select-all">
                        {generatedPaymentId}
                      </div>
                      <span className="text-[9px] text-zinc-500">Matching validation ID</span>
                    </div>
                  </div>

                </div>
              </div>
            )}

            {/* Step 2 Details: Paying with Coins Info */}
            {lotteryNumber.length === 3 && payWithCoins && (
              <div className="space-y-1 animate-in slide-in-from-top-2 duration-150">
                <label className="text-[11px] font-bold text-zinc-400 uppercase tracking-wider block">3. Checkout details</label>
                <div className="rounded-xl border border-amber-500/20 bg-amber-955/5 bg-black/50 p-4 space-y-2.5 font-sans">
                  <div className="flex items-start gap-3">
                    <Trophy className="h-5 w-5 text-amber-400 shrink-0 mt-0.5" />
                    <div className="space-y-0.5">
                      <h4 className="text-[11px] font-extrabold text-amber-400 uppercase tracking-wide">
                        Free Sponsor Pass Active
                      </h4>
                      <p className="text-[10px] text-zinc-405 leading-snug">
                        By spending <strong className="text-amber-305">30 Gold Coins</strong>, you achieve an instant free pass. Bypasses UPI deposit queue entirely! This ticket will be <span className="text-emerald-400 font-bold animate-pulse">Auto-Approved instantly</span>.
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            )}

            {/* Step 3: Transaction ID Input if paying UPI */}
            {lotteryNumber.length === 3 && !payWithCoins && (
              <div className="space-y-2 animate-in slide-in-from-top-2 duration-150">
                <div className="flex items-center justify-between">
                  <label htmlFor="txn-id-input" className="text-[11px] font-bold text-zinc-400 uppercase tracking-wider">3. Enter Transaction ID (Txn ID)</label>
                  <button
                    type="button"
                    onClick={autofillTxnId}
                    className="text-[10px] text-purple-400 hover:text-red-405 transition cursor-pointer font-bold"
                  >
                    [ Use Demo ID ]
                  </button>
                </div>
                <input
                  id="txn-id-input"
                  type="text"
                  value={txnId}
                  onChange={(e) => setTxnId(e.target.value)}
                  placeholder="e.g. UPI8205719"
                  className="w-full rounded-lg bg-black border border-purple-950/30 px-3 py-2 text-xs font-mono text-white placeholder-zinc-700 focus:border-purple-500 focus:outline-none transition"
                />
              </div>
            )}

            {errorMessage && (
              <div className="text-xs text-rose-405 bg-rose-500/5 border border-rose-100/10 p-2.5 rounded-lg">
                {errorMessage}
              </div>
            )}

            <button
              id="submit-ticket-btn"
              type="submit"
              className={`w-full flex items-center justify-center gap-1.5 rounded-lg transition py-2.5 text-xs font-extrabold tracking-wide cursor-pointer ${
                payWithCoins
                  ? "bg-gradient-to-r from-amber-500 via-yellow-500 to-amber-600 hover:from-yellow-500 hover:to-amber-500 text-zinc-950 font-black shadow-[0_0_20px_rgba(245,158,11,0.2)]"
                  : "bg-gradient-to-r from-purple-600 via-fuchsia-600 to-red-655 hover:from-purple-500 hover:to-red-550 text-white shadow-[0_0_15px_rgba(168,85,247,0.15)]"
              }`}
            >
              {payWithCoins ? (
                <>
                  <Trophy className="h-3.5 w-3.5 text-zinc-950 animate-bounce" />
                  <span>Redeem Free Ticket with 30 Coins</span>
                </>
              ) : (
                <>
                  <Send className="h-3.5 w-3.5" />
                  <span>Submit UPI Ticket Registration</span>
                </>
              )}
            </button>

          </form>
        )}
      </div>

    </div>
  );
}
